spring.application.name=Ecommerce
spring.jpa.open-in-view=true
spring.datasource.url=jdbc:mysql://localhost:3306/ecommercelpoo
spring.datasource.username=root
spring.datasource.password=Basutuia@1,

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

